{% set name = "aiohttp-session" %}
{% set version = "2.7.0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 18ae740845214086f783574edfee1bac36862332bd11d561e048b079d8f6ad34

build:
  number: 1
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv "

requirements:
  host:
    - aiohttp >=3.0.1
    - pip
    - python {{ python_min }}
  run:
    - aiohttp >=3.0.1
    - python >={{ python_min }}
  run_constrained:
    - aioredis >=1.0.0
    - aiomcache >=0.5.2

test:
  requires:
    - python {{ python_min }}
  imports:
    - aiohttp_session

about:
  home: https://github.com/aio-libs/aiohttp-session/
  license: Apache Software
  license_family: APACHE
  license_file: LICENSE
  summary: sessions for aiohttp.web
  doc_url: http://aiohttp-session.readthedocs.io/

extra:
  recipe-maintainers:
    - epruesse
